require: 
  - rubocop-rspec
  - rubocop-rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - db/**/*
    - tmp/**/*

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/MultipleMemoizedHelpers:
  Max: 10
