require: 
  - rubocop-rspec
  - rubocop-rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - db/**/*
    - tmp/**/*

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/MessageSpies:
  Exclude:
    - spec/jobs/cats/send_index_result_job_spec.rb

Rails/DeprecatedActiveModelErrorsMethods:
  Exclude:
    # The error handling mechanism in the `dry-rb` library shares an interface with Rails' error handling.
    # However, RuboCop mistakenly assumes that the code within this file is specifically related to Rails.
    # The correction suggested by RuboCop is incompatible with the `dry-rb` library.
    # As a result, the `Rails/DeprecatedActiveModelErrorsMethods` cop has been disabled for
    # the `app/operations/application_operation.rb` file, as it is not applicable in this context.
    - 'app/operations/application_operation.rb'
