require: 
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - db/**/*
    - tmp/**/*

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3
